import "./globals.css"
import { Inter } from "next/font/google"

import { cn } from "@/ui/utils"
import Providers from "@/context/Providers"
import { getServerSession } from "next-auth"
import { authOptions } from "@/utils/next-auth"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en" className="text-sm md:text-base">
      <body className={cn("min-h-screen flex flex-col", inter.className)}>
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  )
}
